# .graphclientrc.yml
sources:
  - name: predict-x
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/94980/predict-x-webhook/0.0.3
plugins:
  - pollingLive:
      defaultInterval: 1000
      includes: ["MarketInitialized", "MarketResolved", "TokensBought", "TokensSold"]